### ISSUE TITLE
Issen't working on IE8+

### ISSUE THREAD

**Issue by maxigimenez** [toddmotto/atomic#13]
I'm getting:
```
Access is denied.
atomic.js, line 43 character 5
```
The error seems to be in the request open.

**Comment by peteringram0** [comment]
+1

**Comment by toddmotto** [comment]
What method are you calling that throws?

On 9 October 2015 at 14:17, Peter Ingram <notifications@github.com> wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toddmotto/atomic/issues/13#issuecomment-146869220>.
>



-- 
@toddmotto

**Comment by maxigimenez** [comment]
The error was in the load of the script, no need to consume any method. 
But IE8 will be deprecated soon by Microsoft, so this issue doesn't have any sense any more :smile:
