### ISSUE TITLE
Missing v1.1.0 tag

### ISSUE THREAD

**Issue by toomuchdesign** [toddmotto/atomic#23]
Hi Todd, v1.1.0 tag is missing among Atomic releases!
It prevents Bower from getting 1.1.0 updates (unless setting the dependency to the last commit).

Not sure if make a pull request for so little thing. Greetings!

**Comment by toddmotto** [comment]
Hey man, sorry took so long, tag is now available: https://github.com/toddmotto/atomic/releases/tag/v1.1.0

Thanks for using Atomic, appreciate the input :)
