### ISSUE TITLE
README.md slight mistake

### ISSUE THREAD

**Issue by dvLden** [toddmotto/atomic#24]
I am not sure if that was intented or it's slight typo out there:

`atomic.post('/endpoint'[, data])`
`atomic.put('/endpoint'[, data])`

`atomic.post('/endpoint', [data])`
`atomic.put('/endpoint', [data])`

**Comment by toddmotto** [comment]
Syntax for showing optional stuff: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
